"use client";

import { useRef, useState } from "react";
import type { RouteActivity } from "@cediah/contracts";
import { nextLocalKeyV2 } from "./editor-model";
import { FieldV2 } from "./sources-fields";
import { choiceCorrectV2, objectiveVerificationOptionsV2 } from "./activity-model";
import type { ActivityFieldsPropsV2 } from "./activity-fields";
import styles from "../route-editor.module.css";
import local from "./styles.module.css";

export function ActivityStudyV2({ activity, pkg, path, issues, onChange }: ActivityFieldsPropsV2<Extract<RouteActivity, { kind: "study" }>>) {
  const bodyRef = useRef<HTMLTextAreaElement>(null);
  const [selection, setSelection] = useState({ start: 0, end: 0 });
  const payload = activity.payload;
  return <div className={local.stack}>
    <p className={styles.fieldHint}>La lectura registra completitud. No acredita dominio del objetivo.</p>
    <FieldV2 label="Contenido de estudio" path={`${path}.payload.body`} issues={issues} hint="Para señalar un fragmento, selecciónalo en el texto y pulsa Añadir señal. Editar el texto retira las señales para volver a ubicarlas.">{(input) => <textarea {...input} ref={bodyRef} required rows={6} maxLength={10000} value={payload.body} onSelect={() => setSelection({ start: bodyRef.current?.selectionStart ?? 0, end: bodyRef.current?.selectionEnd ?? 0 })} onChange={(event) => { onChange({ ...activity, payload: { ...payload, body: event.target.value, focusSpans: [] } }); setSelection({ start: 0, end: 0 }); }} />}</FieldV2>
    <button className={styles.secondaryButton} type="button" disabled={selection.end <= selection.start} onClick={() => { if (selection.end > selection.start && selection.end <= payload.body.length && !payload.focusSpans.some((span) => span.start === selection.start && span.end === selection.end)) onChange({ ...activity, payload: { ...payload, focusSpans: [...payload.focusSpans, selection] } }); bodyRef.current?.focus(); }}>Añadir señal al fragmento seleccionado</button>
    {payload.focusSpans.length ? <ul className={local.linkList} data-field-path={`${path}.payload.focusSpans`} tabIndex={-1}>{payload.focusSpans.map((span, index) => <li key={index}><span>{payload.body.slice(span.start, span.end) || "Señal fuera del texto"}</span><button className={styles.textButton} type="button" aria-label={`Quitar señal ${index + 1}`} onClick={() => { onChange({ ...activity, payload: { ...payload, focusSpans: payload.focusSpans.filter((_, i) => i !== index) } }); bodyRef.current?.focus(); }}>Quitar</button></li>)}</ul> : null}
    <FieldV2 label="Apoyo del ejemplo" path={`${path}.payload.scaffold`} issues={issues}>{(input) => <select {...input} value={payload.scaffold} onChange={(event) => onChange({ ...activity, payload: { ...payload, scaffold: event.target.value as typeof payload.scaffold } })}><option value="explanation">Explicación</option><option value="worked_example">Ejemplo resuelto</option><option value="partial_example">Ejemplo parcial</option></select>}</FieldV2>
    <details className={styles.disclosure}><summary>Recurso visual vinculado</summary><div className={local.activityDetailGrid}>
      <FieldV2 label="Recurso de estudio" path={`${path}.payload.assetKey`} issues={issues}>{(input) => <select {...input} value={payload.assetKey ?? ""} onChange={(event) => onChange({ ...activity, payload: { ...payload, assetKey: event.target.value || null, videoRange: null } })}><option value="">Sin recurso</option>{payload.assetKey && !pkg.assets.some((item) => item.key === payload.assetKey) ? <option value={payload.assetKey}>Recurso ausente: selecciona otro</option> : null}{pkg.assets.map((item) => <option key={item.key} value={item.key}>{item.caption || item.originalFileName}</option>)}</select>}</FieldV2>
      {payload.videoRange ? <div className={styles.fieldGrid}><FieldV2 label="Inicio del fragmento (segundos)" path={`${path}.payload.videoRange.startSeconds`} issues={issues}>{(input) => <input {...input} type="number" min={0} value={payload.videoRange!.startSeconds} onChange={(event) => onChange({ ...activity, payload: { ...payload, videoRange: { ...payload.videoRange!, startSeconds: Number(event.target.value) } } })} />}</FieldV2><FieldV2 label="Fin del fragmento (segundos)" path={`${path}.payload.videoRange.endSeconds`} issues={issues}>{(input) => <input {...input} type="number" min={0} value={payload.videoRange!.endSeconds} onChange={(event) => onChange({ ...activity, payload: { ...payload, videoRange: { ...payload.videoRange!, endSeconds: Number(event.target.value) } } })} />}</FieldV2><button className={styles.textButton} type="button" onClick={() => onChange({ ...activity, payload: { ...payload, videoRange: null } })}>Usar recurso completo</button></div> : null}
    </div></details>
  </div>;
}
export function ActivityChoiceOptionsV2({ activity, path, issues, onChange }: ActivityFieldsPropsV2<Extract<RouteActivity, { kind: "single_choice" }>>) {
  const payload = activity.payload;
  const addRef = useRef<HTMLButtonElement>(null);
  return <div className={local.stack}><h4>Opciones de respuesta</h4>{payload.options.map((option, index) => <div className={local.activityOption} key={option.key}>
    <FieldV2 label={`Opción ${index + 1}`} path={`${path}.payload.options.${index}.text`} issues={issues}>{(input) => <textarea {...input} rows={2} maxLength={2000} required value={option.text} onChange={(event) => onChange({ ...activity, payload: { ...payload, options: payload.options.map((item) => item.key === option.key ? { ...item, text: event.target.value } : item) } })} />}</FieldV2>
    <button className={styles.textButton} type="button" disabled={payload.options.length <= 2 || activity.misconceptionMappings.some((item) => item.responseKey === option.key)} aria-label={`Eliminar opción ${index + 1}`} onClick={() => { const options = payload.options.filter((item) => item.key !== option.key); const correctKey = payload.correctKey === option.key ? options[0]!.key : payload.correctKey; onChange(choiceCorrectV2({ ...activity, payload: { ...payload, options } }, correctKey)); addRef.current?.focus(); }}>Eliminar opción</button>
  </div>)}<button ref={addRef} className={styles.secondaryButton} type="button" disabled={payload.options.length >= 6} onClick={() => { const key = nextLocalKeyV2("opcion", payload.options.map((item) => item.key)); onChange({ ...activity, payload: { ...payload, options: [...payload.options, { key, text: "" }], distractorFeedback: { ...payload.distractorFeedback, [key]: "" } } }); }}>Añadir opción</button></div>;
}
export function ActivityChoiceSolutionV2({ activity, path, issues, onChange }: ActivityFieldsPropsV2<Extract<RouteActivity, { kind: "single_choice" }>>) {
  const payload = activity.payload;
  return <div className={local.stack}><FieldV2 label="Opción correcta" path={`${path}.payload.correctKey`} issues={issues}>{(input) => <select {...input} value={payload.correctKey} onChange={(event) => onChange(choiceCorrectV2(activity, event.target.value))}>{payload.options.map((option, index) => <option key={option.key} value={option.key}>{`Opción ${index + 1}: ${option.text || "sin texto"}`}</option>)}</select>}</FieldV2>
    {payload.options.filter((option) => option.key !== payload.correctKey).map((option) => <FieldV2 key={option.key} label={`Por qué es incorrecta: opción ${payload.options.indexOf(option) + 1}`} path={`${path}.payload.distractorFeedback.${option.key}`} issues={issues} hint="La corrección se fundamenta en las fuentes del feedback seleccionadas abajo.">{(input) => <textarea {...input} required rows={2} maxLength={2000} value={payload.distractorFeedback[option.key] ?? ""} onChange={(event) => onChange({ ...activity, payload: { ...payload, distractorFeedback: { ...payload.distractorFeedback, [option.key]: event.target.value } } })} />}</FieldV2>)}
  </div>;
}
export function ActivityShortSolutionV2({ activity, path, issues, onChange }: ActivityFieldsPropsV2<Extract<RouteActivity, { kind: "short_answer" }>>) {
  const payload = activity.payload;
  const addRef = useRef<HTMLButtonElement>(null);
  return <div className={local.stack}><p className={styles.fieldHint}>Se compara la respuesta completa. Se normalizan mayúsculas y espacios; se conservan acentos, negación y unidades. Las variantes válidas deben estar declaradas.</p>
    <FieldV2 label="Respuesta modelo" path={`${path}.payload.modelAnswer`} issues={issues}>{(input) => <textarea {...input} required rows={2} maxLength={2000} value={payload.modelAnswer} onChange={(event) => onChange({ ...activity, payload: { ...payload, modelAnswer: event.target.value } })} />}</FieldV2>
    <FieldV2 label="Límite de caracteres de la respuesta" path={`${path}.payload.maxChars`} issues={issues}>{(input) => <input {...input} type="number" min={1} max={500} step={1} value={payload.maxChars} onChange={(event) => onChange({ ...activity, payload: { ...payload, maxChars: Number(event.target.value) } })} />}</FieldV2>
    {payload.acceptedAnswers.map((answer, index) => <div className={local.activityOption} key={index}><FieldV2 label={`Respuesta aceptada ${index + 1}`} path={`${path}.payload.acceptedAnswers.${index}`} issues={issues}>{(input) => <input {...input} required maxLength={500} value={answer} onChange={(event) => onChange({ ...activity, payload: { ...payload, acceptedAnswers: payload.acceptedAnswers.map((item, i) => i === index ? event.target.value : item) } })} />}</FieldV2><button type="button" className={styles.textButton} disabled={payload.acceptedAnswers.length <= 1} aria-label={`Eliminar respuesta aceptada ${index + 1}`} onClick={() => { onChange({ ...activity, payload: { ...payload, acceptedAnswers: payload.acceptedAnswers.filter((_, i) => i !== index) } }); addRef.current?.focus(); }}>Eliminar variante</button></div>)}
    <button ref={addRef} className={styles.secondaryButton} disabled={payload.acceptedAnswers.length >= 30} type="button" onClick={() => onChange({ ...activity, payload: { ...payload, acceptedAnswers: [...payload.acceptedAnswers, ""] } })}>Añadir respuesta aceptada</button>
  </div>;
}
export function ActivityConstructedSolutionV2({ activity, pkg, path, issues, onChange }: ActivityFieldsPropsV2<Extract<RouteActivity, { kind: "constructed_response" }>>) {
  const payload = activity.payload;
  const verification = objectiveVerificationOptionsV2(pkg, activity);
  const addRef = useRef<HTMLButtonElement>(null);
  return <div className={local.stack}><p role="note" className={styles.fieldHint}>Respuesta construida o tarjeta: la autoevaluación es formativa y no acredita dominio. El reverso y la rúbrica se muestran al alumno después de responder y revelar.</p>
    <FieldV2 label="Respuesta modelo o reverso de la tarjeta" path={`${path}.payload.modelAnswer`} issues={issues}>{(input) => <textarea {...input} required rows={4} maxLength={4000} value={payload.modelAnswer} onChange={(event) => onChange({ ...activity, payload: { ...payload, modelAnswer: event.target.value } })} />}</FieldV2>
    <h4>Criterios de autoevaluación</h4>{payload.rubric.map((entry, index) => <div key={entry.key} className={local.activitySubcard}><div className={styles.fieldGrid}><FieldV2 label={`Criterio ${index + 1}`} path={`${path}.payload.rubric.${index}.criterion`} issues={issues}>{(input) => <textarea {...input} required rows={2} maxLength={2000} value={entry.criterion} onChange={(event) => onChange({ ...activity, payload: { ...payload, rubric: payload.rubric.map((item) => item.key === entry.key ? { ...item, criterion: event.target.value } : item) } })} />}</FieldV2><FieldV2 label={`Ejemplo del criterio ${index + 1}`} path={`${path}.payload.rubric.${index}.example`} issues={issues}>{(input) => <textarea {...input} required rows={2} maxLength={2000} value={entry.example} onChange={(event) => onChange({ ...activity, payload: { ...payload, rubric: payload.rubric.map((item) => item.key === entry.key ? { ...item, example: event.target.value } : item) } })} />}</FieldV2></div><button className={styles.textButton} type="button" disabled={payload.rubric.length <= 1} aria-label={`Eliminar criterio ${index + 1}`} onClick={() => { onChange({ ...activity, payload: { ...payload, rubric: payload.rubric.filter((item) => item.key !== entry.key) } }); addRef.current?.focus(); }}>Eliminar criterio</button></div>)}
    <button ref={addRef} className={styles.secondaryButton} type="button" disabled={payload.rubric.length >= 8} onClick={() => { const key = nextLocalKeyV2("criterio", payload.rubric.map((item) => item.key)); onChange({ ...activity, payload: { ...payload, rubric: [...payload.rubric, { key, criterion: "", example: "" }] } }); }}>Añadir criterio</button>
    <FieldV2 label="Verificación objetiva del mismo objetivo" path={`${path}.payload.verificationActivityKey`} issues={issues} hint="Los objetivos requeridos necesitan una comprobación objetiva de aprendizaje o unidad. El diagnóstico y las reservas finales y diferidas no se usan aquí.">{(input) => <select {...input} value={payload.verificationActivityKey ?? ""} onChange={(event) => onChange({ ...activity, payload: { ...payload, verificationActivityKey: event.target.value || null } })}><option value="">Pendiente de vincular</option>{payload.verificationActivityKey && !verification.some((item) => item.key === payload.verificationActivityKey) ? <option value={payload.verificationActivityKey}>Vínculo no utilizable: selecciona una comprobación</option> : null}{verification.map((item) => <option key={item.key} value={item.key}>{item.prompt || "Actividad sin consigna"}</option>)}</select>}</FieldV2>
  </div>;
}
