"use client";

import type { RouteActivity } from "@cediah/contracts";
import type { ActivityFieldsPropsV2 } from "./activity-fields";
import { FieldV2 } from "./sources-fields";
import { nextLocalKeyV2 } from "./editor-model";
import styles from "../route-editor.module.css";
import local from "./styles.module.css";
type Match = Extract<RouteActivity, {kind: "match"}>;

export function RelationFieldsV2({ activity, path, issues, onChange, solution = false }: ActivityFieldsPropsV2<Match> & {solution?: boolean}) {
  const p = activity.payload;
  const patch = (values: Partial<Match["payload"]>) => onChange({ ...activity, payload: { ...p, ...values } });
  if (solution) return <div className={local.stack}>
    <h4>Correspondencias correctas</h4><p className={styles.fieldHint}>Cada fila relaciona un enunciado con una opción. Se puede editar íntegramente con teclado.</p>
    <div className={local.relationTable} role="table" aria-label="Tabla de correspondencias" data-field-path={`${path}.payload.correctByPrompt`} tabIndex={-1}><div role="row" className={local.relationRow}><span role="columnheader">Enunciado</span><span role="columnheader">Opción correcta</span></div>
      {p.prompts.map((prompt, i) => <div role="row" key={prompt.key} className={local.relationRow}><span role="cell">{prompt.text || `Enunciado ${i + 1}`}</span><div role="cell"><FieldV2 label={`Correspondencia ${i + 1}`} path={`${path}.payload.correctByPrompt.${prompt.key}`} issues={issues}>{(input) => <select {...input} value={p.correctByPrompt[prompt.key] ?? ""} onChange={(e) => { const map = { ...p.correctByPrompt }; if (e.target.value) map[prompt.key] = e.target.value; else delete map[prompt.key]; patch({ correctByPrompt: map }); }}><option value="">Selecciona una opción</option>{p.choices.map((choice, j) => <option key={choice.key} value={choice.key}>{choice.text || `Opción ${j + 1}`}</option>)}</select>}</FieldV2></div></div>)}
    </div><label className={styles.checkboxRow}><input type="checkbox" data-field-path={`${path}.payload.allowReuse`} checked={p.allowReuse} onChange={(e) => patch({ allowReuse: e.target.checked })} />Permitir reutilizar una opción</label>
    {p.presentation === "causal_map" ? <div className={local.stack}><h4>Relaciones del micro-mapa</h4><p className={styles.fieldHint}>Define las conexiones entre los elementos existentes. Las relaciones pertenecen a la solución editorial.</p>
      {p.edges.map((edge, i) => <div key={i} className={local.activitySubcard}><div className={styles.fieldGrid}>{(["from", "to"] as const).map((side) => <FieldV2 key={side} label={`${side === "from" ? "Origen" : "Destino"} de relación ${i + 1}`} path={`${path}.payload.edges.${i}.${side}`} issues={issues}>{(input) => <select {...input} value={edge[side]} onChange={(e) => patch({ edges: p.edges.map((item, j) => j === i ? { ...item, [side]: e.target.value } : item) })}><option value="">Selecciona un elemento</option>{[...p.prompts, ...p.choices].map((item) => <option key={item.key} value={item.key}>{item.text || item.key}</option>)}</select>}</FieldV2>)}<FieldV2 label={`Relación ${i + 1}`} path={`${path}.payload.edges.${i}.label`} issues={issues}>{(input) => <input {...input} maxLength={500} value={edge.label} onChange={(e) => patch({ edges: p.edges.map((item, j) => j === i ? { ...item, label: e.target.value } : item) })} />}</FieldV2></div><button type="button" className={styles.textButton} onClick={() => patch({ edges: p.edges.filter((_, j) => j !== i) })}>Retirar relación {i + 1}</button></div>)}
      <button type="button" className={styles.secondaryButton} onClick={() => patch({ edges: [...p.edges, { from: "", to: "", label: "" }] })}>Añadir relación</button>
      {p.edges.length ? <ul aria-label="Vista editorial de relaciones">{p.edges.map((edge, i) => <li key={i}>{[...p.prompts, ...p.choices].find((item) => item.key === edge.from)?.text || "Origen pendiente"} → {edge.label || "Relación pendiente"} → {[...p.prompts, ...p.choices].find((item) => item.key === edge.to)?.text || "Destino pendiente"}</li>)}</ul> : null}
    </div> : null}
  </div>;
  return <div className={local.stack}><FieldV2 label="Presentación de relaciones" path={`${path}.payload.presentation`} issues={issues}>{(input) => <select {...input} value={p.presentation} onChange={(e) => patch({ presentation: e.target.value as Match["payload"]["presentation"] })}><option value="pairs">Pares</option><option value="comparison_table">Tabla de comparación</option><option value="causal_map">Micro-mapa causal</option></select>}</FieldV2>
    {p.presentation !== "causal_map" && p.edges.length ? <p role="alert">Hay relaciones del mapa guardadas. <button type="button" className={styles.textButton} onClick={() => patch({ edges: [] })}>Retirar relaciones para usar esta presentación</button></p> : null}
    {(["prompts", "choices"] as const).map((collection) => <div key={collection} className={local.stack}><h4>{collection === "prompts" ? "Enunciados" : "Opciones"}</h4>{p[collection].map((item, i) => <div key={item.key} className={local.activityOption}><FieldV2 label={`${collection === "prompts" ? "Enunciado" : "Opción relacional"} ${i + 1}`} path={`${path}.payload.${collection}.${i}.text`} issues={issues}>{(input) => <textarea {...input} rows={2} maxLength={2000} value={item.text} onChange={(e) => patch({ [collection]: p[collection].map((entry, j) => j === i ? { ...entry, text: e.target.value } : entry) })} />}</FieldV2><button type="button" className={styles.textButton} disabled={p[collection].length <= 1} onClick={() => patch({ [collection]: p[collection].filter((_, j) => j !== i), correctByPrompt: Object.fromEntries(Object.entries(p.correctByPrompt).filter(([key, value]) => collection === "prompts" ? key !== item.key : value !== item.key)), edges: p.edges.filter((edge) => edge.from !== item.key && edge.to !== item.key) })}>Retirar {collection === "prompts" ? "enunciado" : "opción"} {i + 1}</button></div>)}<button type="button" className={styles.secondaryButton} onClick={() => patch({ [collection]: [...p[collection], { key: nextLocalKeyV2(collection === "prompts" ? "enunciado" : "opcion", [...p.prompts, ...p.choices].map((item) => item.key)), text: "" }] })}>Añadir {collection === "prompts" ? "enunciado" : "opción relacional"}</button></div>)}
  </div>;
}
